import express from "express";
import { pool } from "../db";

// Router for the public, unauthenticated anamnese share-link endpoints (mounted
// separately in server.ts, WITHOUT authMiddleware). A parent opens a durable link
// generated by staff (see POST /api/patients/:id/anamnese-share-link) and can view/edit
// only that specific patient's anamnese fields — never other patient data.
export const publicAnamneseRouter = express.Router();

// Exact same 17-column list used by the authenticated CRUD router in anamneses.ts —
// kept in sync by hand since this backend has no shared column-mapping helper.
const ANAMNESE_COLUMNS = [
  "queixa_principal",
  "historia_gestacional",
  "marcos_desenvolvimento",
  "linguagem",
  "sono",
  "alimentacao_seletividade",
  "controle_esfincteriano",
  "historico_medico",
  "medicamentos",
  "terapias_atuais",
  "comportamento_casa",
  "comportamento_escola",
  "interesses_hiperfocos",
  "sensibilidades_sensoriais",
  "pontos_fortes",
  "principais_dificuldades",
  "objetivos_familia",
];

// camelCase (request body / Anamnese TS interface) -> snake_case (DB column), matching
// the mapping already established in src/lib/apiMappers.ts anamneseToApi.
const FIELD_TO_COLUMN: Record<string, string> = {
  queixaPrincipal: "queixa_principal",
  historiaGestacional: "historia_gestacional",
  marcosDesenvolvimento: "marcos_desenvolvimento",
  linguagem: "linguagem",
  sono: "sono",
  alimentacaoSeletividade: "alimentacao_seletividade",
  controleEsfincteriano: "controle_esfincteriano",
  historicoMedico: "historico_medico",
  medicamentos: "medicamentos",
  terapiasAtuais: "terapias_atuais",
  comportamentoCasa: "comportamento_casa",
  comportamentoEscola: "comportamento_escola",
  interessesHiperfocos: "interesses_hiperfocos",
  sensibilidadesSensoriais: "sensibilidades_sensoriais",
  pontosFortes: "pontos_fortes",
  principaisDificuldades: "principais_dificuldades",
  objetivosFamilia: "objetivos_familia",
};

function anamneseRowToPublicFields(row: any | null) {
  if (!row) return null;
  const result: Record<string, string> = {};
  for (const [field, column] of Object.entries(FIELD_TO_COLUMN)) {
    result[field] = row[column] ?? "";
  }
  return result;
}

// ── Simple in-memory sliding-window rate limiter for the public POST endpoint ──
// Mirrors the exact same pattern used for the public forms responses endpoint
// (see backend/routes/forms.ts publicSubmitRateLimiter) — a single-clinic app with
// modest traffic, so an in-process Map is sufficient; no Redis/external store needed.
const RATE_LIMIT_WINDOW_MS = 60_000;
const RATE_LIMIT_MAX_REQUESTS = 10;
const rateLimitHits = new Map<string, number[]>();

function publicSubmitRateLimiter(req: express.Request, res: express.Response, next: express.NextFunction) {
  const ip = req.ip || req.socket.remoteAddress || "unknown";
  const now = Date.now();
  const windowStart = now - RATE_LIMIT_WINDOW_MS;

  const hits = (rateLimitHits.get(ip) || []).filter((t) => t > windowStart);
  if (hits.length >= RATE_LIMIT_MAX_REQUESTS) {
    return res.status(429).json({ error: "Muitas tentativas. Aguarde um instante e tente novamente." });
  }

  hits.push(now);
  rateLimitHits.set(ip, hits);
  next();
}

// GET /:token -> minimal info needed to render the public fill-out form: patientId,
// patientName, and existing anamnese field values (if any) so the form can be
// pre-filled and a parent can update/continue instead of always starting blank.
// Never exposes diagnostico, cid, convenio, financial fields, or any other patient PII.
publicAnamneseRouter.get("/:token", async (req, res) => {
  const [patientRows]: any = await pool.query(
    "SELECT id, nome FROM patients WHERE anamnese_share_token = ?",
    [req.params.token]
  );
  if (patientRows.length === 0) return res.status(404).json({ error: "Link inválido ou expirado" });
  const patient = patientRows[0];

  const [anamneseRows]: any = await pool.query(
    "SELECT * FROM anamneses WHERE patient_id = ?",
    [patient.id]
  );

  res.json({
    patientId: patient.id,
    patientName: patient.nome,
    existingAnamnese: anamneseRows.length > 0 ? anamneseRowToPublicFields(anamneseRows[0]) : null,
  });
});

// POST /:token -> upsert the 17 anamnese fields for the patient tied to this token,
// then record a timeline entry so staff see it. Rate-limited per IP to deter abuse.
publicAnamneseRouter.post("/:token", publicSubmitRateLimiter, async (req, res) => {
  const [patientRows]: any = await pool.query(
    "SELECT id, nome FROM patients WHERE anamnese_share_token = ?",
    [req.params.token]
  );
  if (patientRows.length === 0) return res.status(404).json({ error: "Link inválido ou expirado" });
  const patient = patientRows[0];

  const body = req.body ?? {};
  const columnValues = ANAMNESE_COLUMNS.map((column) => {
    const field = Object.keys(FIELD_TO_COLUMN).find((f) => FIELD_TO_COLUMN[f] === column)!;
    return body[field] ?? null;
  });

  // patient_id UNIQUE on anamneses lets us do a clean atomic upsert instead of a
  // separate select-then-branch (same create-or-update-by-patientId semantics as the
  // client-side saveAnamnese in src/hooks/useAnamneses.ts).
  const insertColumns = ["patient_id", ...ANAMNESE_COLUMNS];
  const insertPlaceholders = insertColumns.map(() => "?").join(", ");
  const updateClause = ANAMNESE_COLUMNS.map((col) => `${col} = VALUES(${col})`).join(", ");

  try {
    await pool.query(
      `INSERT INTO anamneses (${insertColumns.join(", ")}) VALUES (${insertPlaceholders})
       ON DUPLICATE KEY UPDATE ${updateClause}`,
      [patient.id, ...columnValues]
    );

    await pool.query(
      `INSERT INTO timeline_items (patient_id, data, tipo, titulo, descricao, profissional)
       VALUES (?, NOW(), 'Avaliação', 'Anamnese preenchida pela família', ?, ?)`,
      [
        patient.id,
        "A família preencheu ou atualizou a anamnese diretamente pelo link de acesso enviado pela clínica.",
        null,
      ]
    );

    // Never echo back sensitive data — a simple success flag is enough for the public form.
    res.status(201).json({ success: true });
  } catch (err) {
    console.error("Erro ao salvar anamnese via link público:", err);
    res.status(500).json({ error: "Não foi possível salvar suas respostas agora. Tente novamente." });
  }
});
