import express from "express";
import { pool } from "../db";

// Router for the public, unauthenticated registration-update share-link endpoints
// (mounted separately in server.ts, WITHOUT authMiddleware). A parent opens a durable
// link generated by staff (see POST /api/patients/:id/cadastro-share-link) and can
// view/update only general registration fields of that specific EXISTING patient —
// never clinical (diagnostico/cid/medicamentos/historico_clinico), financial, or
// insurance fields, and never other patients' data.
export const publicCadastroRouter = express.Router();

// camelCase (request body) -> snake_case (DB column). Deliberately excludes clinical,
// financial, and insurance columns — those stay staff-only.
const FIELD_TO_COLUMN: Record<string, string> = {
  nome: "nome",
  dataNascimento: "data_nascimento",
  telefone: "telefone",
  email: "email",
  responsavel: "responsavel",
  responsavelParentesco: "responsavel_parentesco",
  escola: "escola",
  anoSerie: "ano_serie",
  professor: "professor",
  coordenador: "coordenador",
};

function patientRowToPublicFields(row: any) {
  const result: Record<string, any> = {};
  for (const [field, column] of Object.entries(FIELD_TO_COLUMN)) {
    result[field] = row[column] ?? "";
  }
  return result;
}

// ── Simple in-memory sliding-window rate limiter for the public POST endpoint ──
// Same pattern used by the public forms/anamnese endpoints (single-clinic app,
// modest traffic — no Redis/external store needed).
const RATE_LIMIT_WINDOW_MS = 60_000;
const RATE_LIMIT_MAX_REQUESTS = 10;
const rateLimitHits = new Map<string, number[]>();

function publicSubmitRateLimiter(req: express.Request, res: express.Response, next: express.NextFunction) {
  const ip = req.ip || req.socket.remoteAddress || "unknown";
  const now = Date.now();
  const windowStart = now - RATE_LIMIT_WINDOW_MS;

  const hits = (rateLimitHits.get(ip) || []).filter((t) => t > windowStart);
  if (hits.length >= RATE_LIMIT_MAX_REQUESTS) {
    return res.status(429).json({ error: "Muitas tentativas. Aguarde um instante e tente novamente." });
  }

  hits.push(now);
  rateLimitHits.set(ip, hits);
  next();
}

// GET /:token -> current values of the editable fields, so the family sees what's
// already on file and can correct/complete only what's missing.
publicCadastroRouter.get("/:token", async (req, res) => {
  const [rows]: any = await pool.query(
    "SELECT * FROM patients WHERE cadastro_share_token = ?",
    [req.params.token]
  );
  if (rows.length === 0) return res.status(404).json({ error: "Link inválido ou expirado" });

  res.json({
    patientId: rows[0].id,
    fields: patientRowToPublicFields(rows[0]),
  });
});

// POST /:token -> updates only the whitelisted registration columns for the patient
// tied to this token, then records a timeline entry so staff see the update.
publicCadastroRouter.post("/:token", publicSubmitRateLimiter, async (req, res) => {
  const [rows]: any = await pool.query(
    "SELECT id, nome FROM patients WHERE cadastro_share_token = ?",
    [req.params.token]
  );
  if (rows.length === 0) return res.status(404).json({ error: "Link inválido ou expirado" });
  const patient = rows[0];

  const body = req.body ?? {};
  const columns = Object.keys(FIELD_TO_COLUMN);
  // COALESCE keeps the existing DB value for any field the family left blank/omitted —
  // a partial submission must never null out data already on file (nome is NOT NULL,
  // and other fields shouldn't be silently erased just because this form didn't ask for them).
  const setClause = columns.map((field) => `${FIELD_TO_COLUMN[field]} = COALESCE(?, ${FIELD_TO_COLUMN[field]})`).join(", ");
  const values = columns.map((field) => (body[field] !== undefined && body[field] !== "" ? body[field] : null));

  try {
    await pool.query(`UPDATE patients SET ${setClause} WHERE id = ?`, [...values, patient.id]);

    await pool.query(
      `INSERT INTO timeline_items (patient_id, data, tipo, titulo, descricao, profissional)
       VALUES (?, NOW(), 'Avaliação', 'Cadastro atualizado pela família', ?, ?)`,
      [
        patient.id,
        "A família atualizou os dados cadastrais diretamente pelo link de acesso enviado pela clínica.",
        null,
      ]
    );

    res.status(201).json({ success: true });
  } catch (err) {
    console.error("Erro ao atualizar cadastro via link público:", err);
    res.status(500).json({ error: "Não foi possível salvar as informações agora. Tente novamente." });
  }
});
